# Generated by Django 4.2.5 on 2024-02-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0002_performance_assign_comment_alter_taskchart_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrapi.teams'),
        ),
    ]
