# Generated by Django 4.2.5 on 2024-02-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0003_projectdetail_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project',
            new_name='projectassigned',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='team',
        ),
    ]
