# Generated by Django 4.2.5 on 2024-02-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0004_rename_project_projectdetail_projectassigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='in_team',
            field=models.BooleanField(default=False),
        ),
    ]
