# Generated by Django 4.2.5 on 2024-02-29 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0005_employee_in_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='teamlead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrapi.teamlead'),
        ),
    ]
