# Generated by Django 4.2.5 on 2024-02-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0008_alter_performance_assign_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_assign',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrapi.projects'),
        ),
    ]
