# Generated by Django 4.2.5 on 2024-02-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0009_alter_project_assign_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='assigned_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrapi.employee'),
        ),
    ]
