# Generated by Django 4.2.5 on 2024-02-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0010_alter_projectdetail_assigned_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchart',
            name='assigned_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrapi.employee'),
        ),
    ]
