# Generated by Django 4.2.5 on 2024-03-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0011_alter_taskchart_assigned_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskchart',
            old_name='days_left',
            new_name='total_days',
        ),
    ]
