# Generated by Django 4.2.5 on 2024-03-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0012_rename_days_left_taskchart_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_assign',
            name='comment',
        ),
    ]
